# Generated by Django 5.0.6 on 2024-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('import_location', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
