# Generated by Django 5.0.6 on 2024-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PRODUITS", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="stocks",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
