# Generated by Django 5.0.4 on 2024-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUITS', '0003_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
