# Generated by Django 5.0.4 on 2024-06-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PRODUITS", "0004_alter_products_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="import_location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_name",
            field=models.CharField(max_length=255),
        ),
    ]
